export const AUTH_GETTING = "AUTH_GETTING";
export const AUTH_GET_SUCCESS = "AUTH_GET_SUCCESS";
export const AUTH_GET_FAILURE = "AUTH_GET_FAILURE";

export const AUTH_SIGNIN_ERROR = "AUTH_SIGNIN_ERROR";
export const AUTH_SIGNIN_SUCCESS = "AUTH_SIGNIN_SUCCESS";
export const AUTH_SIGNIN_FAILURE = "AUTH_SIGNIN_FAILURE";
export const AUTH_SIGNIN_INIT = "AUTH_SIGNIN_INIT";

export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILURE = "AUTH_SIGNUP_FAILURE";
export const AUTH_SIGNUP_INIT = "AUTH_SIGNUP_INIT";

export const AUTH_SIGNOUT = "AUTH_SIGNOUT";

export const AUTH_CHANGE_PW = "AUTH_CHANGE_PW";
export const AUTH_CHANGE_PW_FAILURE = "AUTH_CHANGE_PW_FAILURE";

export const CHANGE_NICKNAME = "CHANGE_NICKNAME";


export const AUTH_INIT = "AUTH_INIT";



export const ARTICLE_GETTING = "ARTICLE_GETTING";
export const ARTICLE_GET_SUCCESS = "ARTICLE_GET_SUCCESS";
export const ARTICLE_GET_FAILURE = "ARTICLE_GET_FAILURE";
export const ARTICLE_INIT = "ARTICLE_INIT";


