export const AUTH_GETTING = "AUTH_GETTING";
export const AUTH_GET_SUCCESS = "AUTH_GET_SUCCESS";
export const AUTH_GET_FAILURE = "AUTH_GET_FAILURE";

export const AUTH_SIGNIN_ERROR = "AUTH_SIGNIN_ERROR";
export const AUTH_SIGNIN_SUCCESS = "AUTH_SIGNIN_SUCCESS";
export const AUTH_SIGNIN_FAILURE = "AUTH_SIGNIN_FAILURE";
export const AUTH_SIGNIN_INIT = "AUTH_SIGNIN_INIT";

export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILURE = "AUTH_SIGNUP_FAILURE";
export const AUTH_SIGNUP_INIT = "AUTH_SIGNUP_INIT";

export const AUTH_SIGNOUT = "AUTH_SIGNOUT";
